version: 2
updates:
- package-ecosystem: nuget
  directory: "/SteamKit2"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: nuget
  directory: "/Resources/ProtobufGen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: nuget
  directory: "/Resources/ProtobufDumper"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-minor", "version-update:semver-patch"]
