name: Build and Archive dropler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore worker dependencies
      run: dotnet restore ./SteamDroplerApi.Worker/SteamDroplerApi.Worker.csproj

    - name: Build linux worker application
      run:  dotnet build ./SteamDroplerApi.Worker/SteamDroplerApi.Worker.csproj --configuration Release --runtime linux-x64 --no-restore --self-contained

    - name: Publish linux worker application
      run: dotnet publish ./SteamDroplerApi.Worker/SteamDroplerApi.Worker.csproj /p:DebugType=None /p:DebugSymbols=false -c Release -r linux-x64 -p:PublishSingleFile=true -o ./output

    - name: Restore api dependencies
      run: dotnet restore ./SteamDroplerApi/SteamDroplerApi.csproj

    - name: Build linux api application
      run:  dotnet build ./SteamDroplerApi/SteamDroplerApi.csproj --configuration Release --runtime linux-x64 --no-restore --self-contained

    - name: Publish linux api application
      run: dotnet publish ./SteamDroplerApi/SteamDroplerApi.csproj /p:DebugType=None /p:DebugSymbols=false -c Release -r linux-x64 -p:PublishSingleFile=true -o ./output

    - name: Create zip archive
      run: zip -r dropler-unix.zip ./output

    - name: Upload zip archive
      uses: actions/upload-artifact@v3
      with:
        name: dropler-unix-zip
        path: dropler-unix.zip
